/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.menus.views;

import java.util.List;
import javax.swing.DefaultListModel;
import restaurant.menus.controllers.MainWindowController;

/**
 *
 * @author Nicolas
 */
public class MainWindow extends javax.swing.JFrame implements MainWindowController.MainWindow {

    private MainWindowController controller;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        searchResult = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newDishItem = new javax.swing.JMenuItem();
        newMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        quitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Helmo - Restaurant");
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        getContentPane().add(searchField, java.awt.BorderLayout.PAGE_START);

        searchResult.setMinimumSize(new java.awt.Dimension(1024, 768));
        scrollPane.setViewportView(searchResult);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        newDishItem.setText("New Dish...");
        newDishItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDishItemActionPerformed(evt);
            }
        });
        jMenu1.add(newDishItem);

        newMenuItem.setText("New Menu...");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newMenuItem);
        jMenu1.add(jSeparator1);

        quitItem.setText("Quit");
        quitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitItemActionPerformed(evt);
            }
        });
        jMenu1.add(quitItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDishItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDishItemActionPerformed
        controller.newDishEvent();
    }//GEN-LAST:event_newDishItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        controller.newMenuEvent();
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void quitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitItemActionPerformed
        controller.quitEvent();
    }//GEN-LAST:event_quitItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.quitEvent();
    }//GEN-LAST:event_formWindowClosing

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if(getName().length() > 3) {
            controller.newSearchEvent();
        }
    }//GEN-LAST:event_searchFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem newDishItem;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem quitItem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField searchField;
    private javax.swing.JList searchResult;
    // End of variables declaration//GEN-END:variables


    @Override
    public void setController(MainWindowController controller) {
        this.controller = controller;
    }

    @Override
    public void setSearchText(String value) {
        this.searchField.setText(value);
    }

    @Override
    public String getSearchText() {
        return this.searchField.getText();
    }

    @Override
    public void setSearchResult(List<String> result) {
        DefaultListModel<String> model = new DefaultListModel<>();
        result.stream().forEach(s -> model.addElement(s));
        searchResult.setModel(model);
    }

    @Override
    public void close() {
        this.dispose();
    }
}
